config/routes.rb
Rails.application.routes.draw do

resources :parks do
  resources :reviews
end
resources :features
resources :parkfeatures
resources :users
resources :sessions


get "/login", to: "sessions#new"
get "/logout", to: "sessions#destroy"

root to: "parks#index"

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :parks
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :parkfeatures, dependent: :destroy
  has_many :parks, through: :parkfeatures
end

app/models/park.rb
class Park < ActiveRecord::Base
  belongs_to :airport
  has_many :parkfeatures
  has_many :reviews
  has_many :features, through: :parkfeatures
  
  validates :name, presence: true
  validates :country, presence: true
end

app/models/park_feature.rb
class Park_Feature < ActiveRecord::Base
  belongs_to :park
  belongs_to :feature
end

app/models/parkfeature.rb
class Parkfeature < ActiveRecord::Base
  belongs_to :park
  belongs_to :feature
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :park
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :require_user

  def current_user
    User.find_by(id: session["user_id"])
  end 

  def require_user
    if current_user.nil?
      redirect_to new_session_path
    end
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  skip_before_action :require_user, only: :show

  def index
    @features = Feature.all
  end

  def show
    @feature = Feature.find_by(id: params["id"])
    @parkfeatures = @feature.parkfeatures
  end

  def new
    @feature = Feature.new
  end

  def create
    feature_params = params.require(:feature).permit(:activity)
    @feature = Feature.create(feature_params)
    redirect_to features_path
  end

  def edit
    @feature = Feature.find_by(id: params["id"])
  end

  def update
    feature_params = params.require(:feature).permit(:activity)
    @feature = Feature.find_by(id: params["id"])
    @feature.update(feature_params)
    redirect_to features_path
  end

  def destroy
    @feature = Feature.find_by(id: params["id"])
    @feature.destroy
    redirect_to features_path
  end

end

app/controllers/final_controller.rb
class FinalController < ApplicationController

def index
  @parks = Park.all
end

def show
    @park = Park.find_by(id: params["id"])
    @park_features = @park.park_features 
  end

def new
  @park = Park.new
end

def create
  park_params = params.require(:park).permit!
  @park = Park.new(park_params)
  if @park.save
    redirect_to final_path
  else
    render text: "FAIL"
  end
end

def edit
  @park = Park.find_by(id: params["id"])
end

def update
  park_params = params.require(:park).permit!
  @park = Park.find_by(id: params["id"])
  @park.update(park_params)
  if @park.valid?
    redirect_to final_path
  else
    render text: "FAIL"
  end
end

def destroy
  @park = Park.find_by(id: params["id"])
  @park.destroy
  redirect_to final_path
end

end

app/controllers/parks_controller.rb
class ParksController < ApplicationController

  skip_before_action :require_user, only: [:index, :show]

def index
  @parks = Park.all
end

def show
    @park = Park.find_by(id: params["id"])
    @parkfeatures = @park.parkfeatures 
end

def new
  @park = Park.new
end

def create
  park_params = params.require(:park).permit(:name)
  Park.create(park_params)
  redirect_to parks_path
end

def edit
  @park = Park.find_by(id: params["id"])
end

def update
  park_params = params.require(:park).permit!
  @park = Park.find_by(id: params["id"])
  @park.update(park_params)
  if @park.valid?
    redirect_to parks_path
  else
    render text: "FAIL"
  end
end

def destroy
  @park = Park.find_by(id: params["id"])
  @park.destroy
  redirect_to parks_path
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_park

  def new
    @review = Review.new
  end

  def create
    review_params = params.require(:review).permit(:body, :rating)
    @review = @park.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to @park, notice: "Thanks for the review!"
    else
      render "new"
    end
  end

  private
  def find_park
    @park = Park.find(params[:park_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false
  skip_before_action :require_user

    # Do authentication
    # Redirect to the root_path
    # Display a notice that login was either successful or unsuccessful
  def create
    user = User.find_by(email: params["email"])
    if user && user.authenticate(params["password"])
      session["user_id"] = user.id
      redirect_to root_path, notice: "sweet, you're in!"
    else
      redirect_to root_path, alert: "No way man."
    end
  end


  def destroy
    # Do sign-out
    session["user_id"] = nil
    redirect_to root_path, notice: "See you later!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params["id"])
  end

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit!
    @user = User.create(user_params)
    if @user.valid?
      redirect_to users_path, notice: "Cool dude!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params["id"])
  end

  def update
    user_params = params.require(:user).permit!
    @user = User.find_by(id: params["id"])
    @user.update(user_params)
    redirect_to users_path
  end

  def destroy
    @user = User.find_by(id: params["id"])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def stars_for(review)
    stars = ""
    review.rating.times do
      stars = stars + '<i class="fa fa-star"></i>'
    end
    stars.html_safe
  end

end

app/views/features/edit.html.erb
<%= form_for @feature do |form| %>
  <div class="form-group">
    <%= form.label :activity %>
    <%= form.text_field :activity, class: "form-control" %>
  </div>
  <%= form.button 'Update Feature', class: "btn btn-success" %>
<% end %>

app/views/features/index.html.erb
<h3 class="page-header">
  All Features
  <span class="pull-right">
    <%= link_to "New Feature", new_feature_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>


<ul>
  <% @features.each do |feature| %>
    <li><%= link_to feature.activity, feature_path(feature) %> <%= link_to "Edit", edit_feature_path(feature) %> <%= link_to "Delete", feature_path(feature), method: :delete, data: { confirm: 'Are you really really really sure?' } %></li>
  <% end %>
</ul>

app/views/features/new.html.erb
<%= form_for @feature do |form| %>
  <div class="form-group">
    <%= form.label :activity %>
    <%= form.text_field :activity, class: "form-control" %>
  </div>
  <%= form.button 'Create Feature', class: "btn btn-success" %>
<% end %>

app/views/features/show.html.erb
<h1>You can do <%= @feature.activity %> in the following parks!</h1>


<ul>
  <% @parkfeatures.each do |parkfeature| %>
    <li><%= link_to parkfeature.park.name, park_path(parkfeature.park) %></li>
  <% end %>
</ul>

app/views/final/index.html.erb
<div class="row">
  <% @parks.each do |park| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to image_tag(park.image), final_path(park) %>
        <div class="caption">
          <h3><%= link_to park.name, final_path(park) %></h3>
          <p><%= park.summary %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/final/new.html.erb
<%= form_for @park do |form| %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.text_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :country %>
    <%= form.text_field :country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.text_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: "form-control", rows: 5 %>
  </div>

  <div class="form-group">
    <%= form.label :airport_id %>
    <%= form.collection_select :airport_id, Airport.order(:name), :id, :name, { include_blank: true }, { class: "form-control" } %>
  </div>

  </div>
  <%= form.button 'Create Park', class: "btn btn-success" %>

<% end %>

app/views/final/show.html.erb
<h1 class="title">
   <%= @park.name %>
  <span class="rating"><%= @park.rating %></span>
</h1>

<div class="row">
  <div class="col-md-3 text-center">
    <p><%= imagine_tag @park.image %>></p>
    <p><strong>State:</strong> <%= @park.state %></p>
    <p><strong>Country:</strong> <%= @park.country %></p>
  </div>
  <div class="col-md-4 summary">
    <h2>Summary</h2>
    <p> <%= @park.summary %></p>
  </div>
  <div class="col-md-3 actors">
    <h2>Park Features</h2>
    <ul class="list-unstyled">
      <%= @park_features.each do |park_feature| %>
      <li><%= Feature.find_by(id: park_feature.feature_id).name %></li>
      <% end%>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-9 col-md-offset-3 reviews">
    <h2 class="page-header">Transportation</h2>
    <table class="table table-striped table-bordered">
      <tr>
        <td><strong>Nearest Airport</strong></td>
        <td><%= @park.airport.name %></td>
      </tr>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>National Parks</title>
    <!-- Logo Font -->
    <link href="http://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet" type="text/css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">

      <!-- Alerts -->
      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      
      <nav class="navbar navbar-inverse" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Rails equivalent to -->
          <!-- <a href="/" class="navbar-brand">Buyflix</a> -->
          <%= link_to "National Parks", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="/">
                <i class="fa fa-home"></i>
                Home
              </a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <i class="fa fa-film"></i>
                States
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">California</a></li>
                <li><a href="#">Utah</a></li>
                <li><a href="#">Wyoming</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <i class="fa fa-cog"></i>
                Admin
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Features", features_path %></li>
                <li><%= link_to "New Park", new_park_path %></li>
                <li><%= link_to "Users", users_path %></li>
              </ul>
            </li>
            <li>
                <% if current_user %>
                  <a href="#">Hi, <%= current_user.try(:name) %></a>
                <% else %>
                  <%= link_to "Log In", login_path %>
                <% end %>
            </li>
            <li>
                <% if current_user %>
                  <%= link_to "Log Out", logout_path %>
                <% end %>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/parks/index.html.erb
<div class="row">
  <% @parks.each do |park| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to image_tag(park.image), park_path(park) %>
        <div class="caption">
          <h3><%= link_to park.name, park_path(park) %></h3>
          <p><%= park.summary %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/parks/new.html.erb
<%= form_for @park do |form| %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.text_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :country %>
    <%= form.text_field :country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.text_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: "form-control", rows: 5 %>
  </div>

  <div class="form-group">
    <%= form.label :airport_id %>
    <%= form.collection_select :airport_id, Airport.order(:name), :id, :name, { include_blank: true }, { class: "form-control" } %>
  </div>

  </div>
  <%= form.button 'Create Park', class: "btn btn-success" %>

<% end %>

app/views/parks/show.html.erb
<h1 class="title">
   <%= @park.name %>
  <span class="rating"><%= @park.rating %></span>
</h1>

<div class="row">
  <div class="col-md-3 text-center">
    <p><%= image_tag @park.image, class: "poster" %>></p>
    <p><strong>State:</strong> <%= @park.state %></p>
    <p><strong>Country:</strong> <%= @park.country %></p>
  </div>
  <div class="col-md-4 summary">
    <h2>Summary</h2>
    <p> <%= @park.summary %></p>
  </div>
  <div class="col-md-3 actors">
    <h2>Park Features</h2>
    <ul class="list-unstyled">
      <%= @parkfeatures.each do |parkfeature| %>
      <li><%= link_to parkfeature.feature.activity, feature_path(parkfeature.feature) %></li>
      <% end%>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-3">
    <h3>Reviews</h3>
    <% @park.reviews.each do |review| %>
      <h4><%= review.user.name %> <%= stars_for(review) %></h4>
      <p><%= review.body %></p>
    <% end %>

    <%= link_to "Write a Review", new_park_review_path(@park), class: 'btn btn-success' %>
  </div>
</div>

<div class="row">
  <div class="col-md-9 col-md-offset-3 reviews">
    <h2 class="page-header">Transportation</h2>
    <table class="table table-striped table-bordered">
      <tr>
        <td><strong>Nearest Airport</strong></td>
        <td><%= @park.airport.name %></td>
      </tr>
    </table>
  </div>
</div>

app/views/reviews/new.html.erb
<%= form_for [@park, @review] do |form| %>
  <div class="form-group">
    <%= form.label :rating %>
    <%= form.select :rating, [1,2,3,4,5], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>
  <%= form.button 'Post Your Review', class: "btn btn-success" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <%= form.button 'Update', class: "btn btn-success" %>
<% end %>

app/views/users/index.html.erb
<h3 class="page-header">
  All Users
  <span class="pull-right">
    <%= link_to "New User", new_user_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> <%= link_to "Edit", edit_user_path(user) %> <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<!-- 
  Finish the signup form
  Validate that the email, password, and name are present
-->

<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <%= form.button 'Sign Up', class: "btn btn-success" %>
<% end %>